# Generated by Django 6.1.2 on 2026-10-09 09:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PronPhrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_en",
                    models.CharField(max_length=200, verbose_name="Sentensa (Inglés)"),
                ),
                (
                    "text_tet",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Tradusaun (Tetun)"
                    ),
                ),
                (
                    "band",
                    models.CharField(
                        choices=[
                            ("beginner", "Hahú (A1-A2)"),
                            ("intermediate", "Média (B1-B2)"),
                            ("advanced", "Avansadu (C1-C2)"),
                        ],
                        default="beginner",
                        max_length=12,
                        verbose_name="Band nível",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativu")),
            ],
            options={
                "verbose_name": "Sentensa pronunciation",
                "verbose_name_plural": "Sentensa pronunciation",
                "ordering": ["band", "id"],
            },
        ),
        migrations.CreateModel(
            name="PronAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transcript",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Neʼebé rona"
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Konfiansa rekonhesedór"
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(verbose_name="Pontu")),
                (
                    "detail",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Detalle liafuan"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Data",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pron_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudante",
                    ),
                ),
                (
                    "phrase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pronounce.pronphrase",
                        verbose_name="Sentensa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tentativa pronunciation",
                "verbose_name_plural": "Tentativa pronunciation",
                "ordering": ["-created_at"],
            },
        ),
    ]
