# Generated by Django 6.1.2 on 2026-10-09 09:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("chat", "Ngobrol bebas"),
                            ("situasaun", "Situasaun"),
                            ("vocab", "Kosa kata"),
                            ("grammar", "Grammar fix"),
                            ("quiz", "Quiz"),
                            ("pron", "Pronunciation"),
                        ],
                        max_length=10,
                        verbose_name="Tipu",
                    ),
                ),
                (
                    "points",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Pontu"),
                ),
                (
                    "ref",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Referénsia"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Data",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atividade",
                "verbose_name_plural": "Atividade",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=2, verbose_name="Nível")),
                (
                    "code",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="Kódigu verifikasaun"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Naran iha sertifikadu"
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data emite"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sertifikadu",
                "verbose_name_plural": "Sertifikadu",
                "ordering": ["-issued_at"],
                "unique_together": {("user", "level")},
            },
        ),
    ]
