# Generated by Django 6.1.2 on 2026-10-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("chat", "Ngobrol bebas"),
                    ("situasaun", "Situasaun"),
                    ("vocab", "Vokabulario"),
                    ("grammar", "Grammar fix"),
                    ("quiz", "Quiz"),
                    ("pron", "Pronunciation"),
                ],
                max_length=10,
                verbose_name="Tipu",
            ),
        ),
    ]
