# Generated by Django 6.1.2 on 2026-10-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="best_streak",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Streak di'ak liu"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_active",
            field=models.DateField(
                blank=True, null=True, verbose_name="Loron ativu ikus"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="points",
            field=models.PositiveIntegerField(default=0, verbose_name="Pontu"),
        ),
        migrations.AddField(
            model_name="user",
            name="streak",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Streak (loron-loron)"
            ),
        ),
    ]
