# Generated by Django 6.1.2 on 2026-10-09 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0001_initial"),
        ("users", "0003_user_best_streak_user_last_active_user_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="custom.municipality",
                verbose_name="Munisipiu",
            ),
        ),
    ]
