# Generated by Django 6.1.2 on 2026-10-09 09:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="Kódigu")),
                ("label", models.CharField(max_length=40, verbose_name="Naran pakote")),
                ("hours", models.PositiveIntegerField(verbose_name="Oras")),
                (
                    "price_usd",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Folin (USD)"
                    ),
                ),
                (
                    "sort",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativu")),
            ],
            options={
                "verbose_name": "Pakote",
                "verbose_name_plural": "Pakote",
                "ordering": ["sort"],
            },
        ),
        migrations.CreateModel(
            name="Entitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Remata iha")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlement",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asesu pakote",
                "verbose_name_plural": "Asesu pakote",
            },
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Kódigu"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data kria"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data uza"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="billing.plan",
                        verbose_name="Pakote",
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uza husi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaucher",
                "verbose_name_plural": "Vaucher",
            },
        ),
        migrations.CreateModel(
            name="UsageDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(verbose_name="Loron")),
                ("turns", models.PositiveIntegerField(default=0, verbose_name="Dalan")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uzu loron-loron",
                "verbose_name_plural": "Uzu loron-loron",
                "unique_together": {("user", "day")},
            },
        ),
    ]
