"""Semua teks antarmuka (Tetun) di satu tempat supaya mudah ditinjau penutur asli.

CATATAN: ditulis sebaik mungkin, WAJIB ditinjau penutur asli Tetun sebelum peluncuran.
Placeholder {n}, {email}, {date} diisi oleh JavaScript.
"""
TETUN = {
    'app_name': 'Lafex',
    'mascot_alt': 'Maun Lafaek, ita-nia tutór',
    'back': 'Fila fali',
    'logout': 'Sai',
    'loading': 'Hein uitoan...',
    'nav_home': 'Uma',
    'nav_review': 'Revisaun',
    'nav_admin': 'Admin',
    'err_forbidden': 'Ita la iha autorizasaun atu loke pájina ne\'e.',
    'err_not_found': 'Pájina la hetan.',

    # Login
    'login_title': 'Tama ba Lafex',
    'login_sub': 'Hakerek ita-nia email. Ami haruka kódigu númeru 6.',
    'email_label': 'Email',
    'send_code': 'Haruka kódigu',
    'code_label': 'Kódigu husi email',
    'code_sent': 'Ami haruka kódigu ba {email}. Haree iha inbox no spam.',
    'enter': 'Tama',
    'resend': 'Haruka fali kódigu',
    'err_email_invalid': 'Email la loos.',
    'err_rate_limited': 'Husu kódigu barak liu. Hein oras ida.',
    'err_code_wrong': 'Kódigu sala ka expira ona.',
    'err_code_invalid': 'Kódigu iha númeru 6.',

    # Beranda
    'greeting': 'Olá! Hau Maun Lafaek, ita-nia tutór Inglés.',
    'placement_cta': 'Hahú ho teste nível (minutu 3)',
    'level_label': 'Nível',
    'scenarios_title': 'Hili situasaun',
    'band_beginner': 'Hahú (A1-A2)',
    'band_intermediate': 'Média (B1-B2)',
    'band_advanced': 'Avansadu (C1-C2)',
    'recommended': 'Rekomenda',
    'best_score': 'Pontu di\'ak liu',
    'access_active': 'Pakote ativu to\'o {date}',
    'access_free': 'Dalan gratis ohin loron: {n}',
    'buy_title': 'Pakote no kódigu vaucher',
    'voucher_label': 'Kódigu vaucher',
    'redeem': 'Uza kódigu',
    'redeemed': 'Pakote aumenta ona!',
    'review_link': 'Revisaun (mós bele offline)',
    'err_voucher_unknown': 'Kódigu la existe.',
    'err_voucher_void': 'Kódigu ne\'e kansela ona.',
    'err_voucher_expired': 'Kódigu ne\'e expira ona.',
    'err_voucher_used': 'Kódigu ne\'e uza tiha ona.',

    # Misi
    'goal': 'Objetivu',
    'start_mission': 'Hahú',
    'tap': 'Klik botaun atu ko\'alia',
    'listening': 'Hau rona...',
    'thinking': 'Hanoin...',
    'speaking': 'Maun Lafaek ko\'alia...',
    'repeat': 'Repete',
    'handsfree': 'Laiha liman (automátiku)',
    'slow': 'Neineik',
    'send': 'Haruka',
    'finish': 'Remata no haree rezultadu',
    'you': 'Ita',
    'tutor': 'Maun Lafaek',
    'fix': 'Koreksaun',
    'no_stt': 'Browser ne\'e la suporta rona lian. Hakerek de\'it.',
    'no_voice': 'Aparellu ne\'e la iha lian Inglés. Maun Lafaek sei hatudu de\'it teksto.',
    'no_speech': 'Hau la rona. Klik botaun fali.',
    'mission_full': 'Misaun ne\'e kompletu ona. Klik "Remata".',
    'err_no_access': 'Dalan gratis ohin remata. Uza kódigu vaucher atu kontinua.',
    'err_daily_limit': 'Limite loron ida remata. Fila fali aban.',
    'err_tutor_failed': 'Sistema falla. Koko fali.',
    'err_refused': 'Maun Lafaek la bele hatán ba ne\'e.',
    'err_busy': 'Sistema okupadu. Koko fali.',
    'err_generic': 'Iha problema. Koko fali.',

    # Resultadu
    'result_title': 'Rezultadu',
    'score': 'Pontu',
    'new_level': 'Ita-nia nível agora',
    'tips': 'Konsellu',
    'vocab': 'Liafuan foun',
    'corrections': 'Koreksaun',
    'to_home': 'Fila ba uma',

    # Revisaun
    'review_title': 'Revisaun',
    'review_empty': 'Seidauk iha misaun ne\'ebé remata.',
    'review_locked': 'Pakote remata ona. Sosa pakote foun atu loke revisaun.',
    'review_clock': 'Oras telemóvel la loos. Konekta ba internet atu sinkroniza.',
    'review_offline': 'Offline: hatudu dadus ne\'ebé rai tiha ona iha telemóvel.',
    'review_need_online': 'Konekta ba internet uluk atu rai revisaun iha telemóvel.',
    'review_saved': 'Rai tiha ona iha telemóvel.',


    'tagline': 'Tutór Inglés',
    'nav_dashboard': 'Painel',
    'nav_students': 'Estudante',
    'nav_missions': 'Misaun',
    'nav_vouchers': 'Vaucher',
    'nav_account': 'Konta',
    'nav_menu': 'Menu',

    # Menu siswa
    'nav_learn': 'Aprende',
    'nav_chat': 'Ngobrol bebas',
    'nav_situations': 'Situasaun',
    'nav_vocab': 'Vokabulario',
    'nav_grammar': 'Grammar fix',
    'nav_practice': 'Treinu',
    'nav_quiz': 'Avaliasaun Quiz',
    'nav_pron': 'Ezame pronunciation',
    'nav_profile': 'Perfíl',
    'nav_student_mode': 'Modu estudante',
    # Menu pendek (sidebar HP)
    'sb_chat': 'Ngobrol', 'sb_situations': 'Situasaun', 'sb_vocab': 'Vokabulario', 'sb_grammar': 'Grammar',
    'sb_quiz': 'Avaliasaun', 'sb_pron': 'Pronun.', 'sb_profile': 'Perfíl', 'sb_review': 'Revisaun',
    'sb_dashboard': 'Painel', 'sb_students': 'Estudante', 'sb_materials': 'Materia', 'sb_quizq': 'Perg.',
    'sb_monchat': 'Chat', 'sb_monpron': 'Pronun.', 'sb_config': 'Konfig.', 'sb_vouchers': 'Vaucher',
    'sb_learn_sec': 'Aprende', 'sb_practice_sec': 'Treinu', 'sb_admin_sec': 'Admin',
    # Menu admin/guru
    'nav_master': 'Master data',
    'nav_students_manage': 'Jere estudante',
    'nav_materials': 'Materia no vokabulario',
    'nav_quiz_questions': 'Pergunta quiz',
    'nav_monitoring': 'Monitorizasaun',
    'nav_mon_chat': 'Chat estudante ho Maun Lafaek',
    'nav_mon_pron': 'Pontu pronunciation ki\'ik liu',
    'nav_settings': 'Konfigurasaun sistema',
    'nav_settings_group': 'Konfigurasaun',
    # Beranda siswa
    'streak': 'Streak',
    'streak_days': '{n} loron',
    'points': 'Pontu',
    'free_mode': 'Modu gratis: ita bele aprende livre.',
    'card_chat': 'Ngobrol bebas', 'card_chat_d': 'Koalia ho Maun Lafaek (hakerek ka lian)',
    'card_vocab': 'Vokabulario', 'card_vocab_d': 'Tetun -> Inglés: eskola, merkadu, kantór',
    'card_grammar': 'Grammar fix', 'card_grammar_d': 'Hakerek sentensa, Maun Lafaek korrije',
    'card_quiz': 'Avaliasaun Quiz', 'card_quiz_d': 'Perguntas lalais, hetan pontu',
    'card_pron': 'Ezame pronunciation', 'card_pron_d': 'Hatete sentensa, hetan pontu',
    'situations_title': 'Situasaun (role-play)',
    'situations_intro': 'Hili situasaun no koalia ho Maun Lafaek.',
    # Vokabulario
    'vocab_title': 'Vokabulario Tetun -> Inglés',
    'vocab_pick': 'Hili kategoria',
    'vocab_known': 'hatene ona',
    'vocab_show': 'Haree tradusaun',
    'vocab_i_know': 'Hau hatene',
    'vocab_not_yet': 'Seidauk',
    'vocab_done': 'Remata! Di\'ak loos.',
    'vocab_again': 'Aprende fali',
    'vocab_empty': 'Kategoria ida-ne\'e seidauk iha vokabulario.',
    'vocab_say': 'Rona',
    # Grammar
    'grammar_title': 'Grammar fix',
    'grammar_intro': 'Hakerek sentensa Inglés. Maun Lafaek sei korrije.',
    'grammar_placeholder': 'Ezemplu: I go to school yesterday',
    'grammar_check': 'Korrije',
    'grammar_ok': 'Sentensa loos ona! Parabéns.',
    'grammar_better': 'Versaun loos',
    'grammar_errors': 'Sala sira',
    'grammar_points': '+{n} pontu',
    # Quiz
    'quiz_title': 'Avaliasaun Quiz',
    'quiz_intro': 'Perguntas 10, tempu minutu 5. Pontu 2 kada resposta loos.',
    'quiz_start': 'Hahú quiz',
    'quiz_time': 'Tempu',
    'quiz_submit': 'Haruka resposta',
    'quiz_result': 'Rezultadu avaliasaun',
    'quiz_correct': 'Loos',
    'quiz_late': 'Tempu liu ona: pontu la hetan.',
    'quiz_none': 'Seidauk iha pergunta. Husu ba profesór.',
    'quiz_answered': 'Resposta',
    # Pronunciation
    'pron_title': 'Ezame pronunciation',
    'pron_intro': 'Rona sentensa, depois hatete. Sistema sei hatudu liafuan ne\'ebé rona loos.',
    'pron_start': 'Hahú ezame',
    'pron_listen': 'Rona ezemplu',
    'pron_record': 'Hatete agora',
    'pron_next': 'Tuir',
    'pron_result': 'Rezultadu ezame',
    'pron_avg': 'Pontu média',
    'pron_note': 'Pontu ne\'e estimativa husi rekonhesedór lian iha telemóvel; la mak avaliasaun profesionál.',
    'pron_ok': 'Loos', 'pron_close': 'Besik', 'pron_missed': 'La rona',
    'pron_no_stt': 'Browser ne\'e la suporta rona lian. Uza Chrome iha Android.',
    'pron_none': 'Seidauk iha sentensa. Husu ba profesór.',
    'pron_heard': 'Hau rona',
    # Perfíl
    'profile_title': 'Ha\'u-nia perfíl',
    'profile_name': 'Naran (ba sertifikadu)',
    'profile_save': 'Rai',
    'profile_saved': 'Rai tiha ona.',
    'profile_level': 'Nível',
    'profile_best_streak': 'Streak di\'ak liu',
    'profile_certs': 'Sertifikadu',
    'profile_no_certs': 'Seidauk iha. Hetan nível foun liu husi situasaun.',
    'profile_view_cert': 'Haree / imprime',
    'profile_privacy': 'Hatene: profesór bele haree ita-nia chat ho Maun Lafaek atu ajuda ita aprende.',
    'cert_title': 'SERTIFIKADU',
    'cert_awarded': 'Fó ba',
    'cert_for': 'ba nível Inglés',
    'cert_date': 'Data',
    'cert_code': 'Kódigu verifikasaun',
    'cert_print': 'Imprime',
    'cert_unnamed': 'Estudante Lafex',
    'new_certificate': 'Sertifikadu foun! Haree iha Perfíl.',
    'points_earned': '+{n} pontu',
    'profile_municipality': 'Munisipiu',
    'profile_municipality_pick': '(hili ita-nia munisipiu)',
    'home_pick_municipality': 'Hili ita-nia munisipiu iha Perfíl.',
    'err_municipality_invalid': 'Munisipiu la loos.',
    'dash_map_title': 'Estudante tuir munisipiu',
    'dash_map_none': 'Seidauk hili munisipiu',
    'login_with': 'Tama ho',
    'login_or': 'ka tama ho email',
    'err_social_error': 'Tama ho konta la konsege. Koko fali ka uza email.',
    'err_social_cancelled': 'Tama ho konta kansela ona.',
    'err_social_no_email': 'Konta ne\'e la fó email. Uza konta seluk ka tama ho email.',
}
