"""Semua teks antarmuka (Tetun) di satu tempat supaya mudah ditinjau penutur asli.

CATATAN: ditulis sebaik mungkin, WAJIB ditinjau penutur asli Tetun sebelum peluncuran.
Placeholder {n}, {email}, {date} diisi oleh JavaScript.
"""
TETUN = {
    'app_name': 'Lafex',
    'mascot_alt': 'Lafaek, ita-nia tutór',
    'back': 'Fila fali',
    'logout': 'Sai',
    'loading': 'Hein uitoan...',
    'nav_home': 'Uma',
    'nav_review': 'Revisaun',
    'nav_admin': 'Admin',
    'err_forbidden': 'Ita la iha autorizasaun atu loke pájina ne\'e.',
    'err_not_found': 'Pájina la hetan.',

    # Login
    'login_title': 'Tama ba Lafex',
    'login_sub': 'Hakerek ita-nia email. Ami haruka kódigu númeru 6.',
    'email_label': 'Email',
    'send_code': 'Haruka kódigu',
    'code_label': 'Kódigu husi email',
    'code_sent': 'Ami haruka kódigu ba {email}. Haree iha inbox no spam.',
    'enter': 'Tama',
    'resend': 'Haruka fali kódigu',
    'err_email_invalid': 'Email la loos.',
    'err_rate_limited': 'Husu kódigu barak liu. Hein oras ida.',
    'err_code_wrong': 'Kódigu sala ka expira ona.',
    'err_code_invalid': 'Kódigu iha númeru 6.',

    # Beranda
    'greeting': 'Olá! Hau Lafaek, ita-nia tutór Inglés.',
    'placement_cta': 'Hahú ho teste nível (minutu 3)',
    'level_label': 'Nível',
    'scenarios_title': 'Hili situasaun',
    'band_beginner': 'Hahú (A1-A2)',
    'band_intermediate': 'Média (B1-B2)',
    'band_advanced': 'Avansadu (C1-C2)',
    'recommended': 'Rekomenda',
    'best_score': 'Pontu di\'ak liu',
    'access_active': 'Pakote ativu to\'o {date}',
    'access_free': 'Dalan gratis ohin loron: {n}',
    'buy_title': 'Pakote no kódigu vaucher',
    'voucher_label': 'Kódigu vaucher',
    'redeem': 'Uza kódigu',
    'redeemed': 'Pakote aumenta ona!',
    'review_link': 'Revisaun (mós bele offline)',
    'err_voucher_unknown': 'Kódigu la existe.',
    'err_voucher_used': 'Kódigu ne\'e uza tiha ona.',

    # Misi
    'goal': 'Objetivu',
    'start_mission': 'Hahú',
    'tap': 'Klik botaun atu ko\'alia',
    'listening': 'Hau rona...',
    'thinking': 'Hanoin...',
    'speaking': 'Lafaek ko\'alia...',
    'repeat': 'Repete',
    'handsfree': 'Laiha liman (automátiku)',
    'slow': 'Neineik',
    'send': 'Haruka',
    'finish': 'Remata no haree rezultadu',
    'you': 'Ita',
    'tutor': 'Lafaek',
    'fix': 'Koreksaun',
    'no_stt': 'Browser ne\'e la suporta rona lian. Hakerek de\'it.',
    'no_voice': 'Aparellu ne\'e la iha lian Inglés. Lafaek sei hatudu de\'it teksto.',
    'no_speech': 'Hau la rona. Klik botaun fali.',
    'mission_full': 'Misaun ne\'e kompletu ona. Klik "Remata".',
    'err_no_access': 'Dalan gratis ohin remata. Uza kódigu vaucher atu kontinua.',
    'err_daily_limit': 'Limite loron ida remata. Fila fali aban.',
    'err_tutor_failed': 'Sistema falla. Koko fali.',
    'err_refused': 'Lafaek la bele hatán ba ne\'e.',
    'err_busy': 'Sistema okupadu. Koko fali.',
    'err_generic': 'Iha problema. Koko fali.',

    # Resultadu
    'result_title': 'Rezultadu',
    'score': 'Pontu',
    'new_level': 'Ita-nia nível agora',
    'tips': 'Konsellu',
    'vocab': 'Liafuan foun',
    'corrections': 'Koreksaun',
    'to_home': 'Fila ba uma',

    # Revisaun
    'review_title': 'Revisaun',
    'review_empty': 'Seidauk iha misaun ne\'ebé remata.',
    'review_locked': 'Pakote remata ona. Sosa pakote foun atu loke revisaun.',
    'review_clock': 'Oras telemóvel la loos. Konekta ba internet atu sinkroniza.',
    'review_offline': 'Offline: hatudu dadus ne\'ebé rai tiha ona iha telemóvel.',
    'review_need_online': 'Konekta ba internet uluk atu rai revisaun iha telemóvel.',
    'review_saved': 'Rai tiha ona iha telemóvel.',


    'tagline': 'Tutór Inglés',
    'nav_dashboard': 'Painel',
    'nav_students': 'Estudante',
    'nav_missions': 'Misaun',
    'nav_vouchers': 'Vaucher',
    'nav_account': 'Konta',
    'nav_menu': 'Menu',
}
