# Generated by Django 6.1.2 on 2026-10-09 09:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VocabCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Kódigu")),
                (
                    "name_tet",
                    models.CharField(max_length=60, verbose_name="Naran (Tetun)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=60, verbose_name="Naran (Inglés)"),
                ),
                (
                    "emoji",
                    models.CharField(blank=True, max_length=8, verbose_name="Emoji"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativu")),
            ],
            options={
                "verbose_name": "Kategoria kosa kata",
                "verbose_name_plural": "Kategoria kosa kata",
                "ordering": ["order", "name_tet"],
            },
        ),
        migrations.CreateModel(
            name="VocabItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tet", models.CharField(max_length=80, verbose_name="Tetun")),
                ("en", models.CharField(max_length=80, verbose_name="Inglés")),
                (
                    "example_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Ezemplu sentensa (Inglés)",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativu")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="vocab.vocabcategory",
                        verbose_name="Kategoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kosa kata",
                "verbose_name_plural": "Kosa kata",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserVocab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "known",
                    models.BooleanField(default=False, verbose_name="Hatene ona"),
                ),
                (
                    "rewarded",
                    models.BooleanField(default=False, verbose_name="Pontu fó ona"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Atualiza"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudante",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vocab.vocabitem",
                        verbose_name="Kosa kata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progresu kosa kata",
                "verbose_name_plural": "Progresu kosa kata",
                "unique_together": {("user", "item")},
            },
        ),
    ]
