# Generated by Django 6.1.2 on 2026-10-09 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uservocab",
            options={
                "verbose_name": "Progresu vokabulario",
                "verbose_name_plural": "Progresu vokabulario",
            },
        ),
        migrations.AlterModelOptions(
            name="vocabcategory",
            options={
                "ordering": ["order", "name_tet"],
                "verbose_name": "Kategoria vokabulario",
                "verbose_name_plural": "Kategoria vokabulario",
            },
        ),
        migrations.AlterModelOptions(
            name="vocabitem",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Vokabulario",
                "verbose_name_plural": "Vokabulario",
            },
        ),
        migrations.AlterField(
            model_name="uservocab",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="vocab.vocabitem",
                verbose_name="Vokabulario",
            ),
        ),
    ]
