# Generated by Django 6.1.2 on 2026-10-09 09:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level_start",
                    models.CharField(max_length=2, verbose_name="Nível hahú"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Hahú"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Remata"),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Pontu"
                    ),
                ),
                (
                    "level_end",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Nível remata"
                    ),
                ),
                (
                    "summary",
                    models.JSONField(blank=True, default=dict, verbose_name="Rezumu"),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="curriculum.mission",
                        verbose_name="Misaun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesaun",
                "verbose_name_plural": "Sesaun",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Turn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idx", models.PositiveSmallIntegerField(verbose_name="Orden")),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "Estudante"), ("assistant", "Lafaek")],
                        max_length=9,
                        verbose_name="Papél",
                    ),
                ),
                ("text", models.TextField(verbose_name="Teksu")),
                ("correction", models.TextField(blank=True, verbose_name="Koreksaun")),
                (
                    "explanation",
                    models.TextField(blank=True, verbose_name="Esplikasaun"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data kria"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="tutor.session",
                        verbose_name="Sesaun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dalan koalia",
                "verbose_name_plural": "Dalan koalia",
                "ordering": ["idx"],
            },
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["user", "finished_at"], name="tutor_sessi_user_id_ee76c7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="turn",
            unique_together={("session", "idx")},
        ),
    ]
