# Generated by Django 6.1.2 on 2026-10-09 09:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GrammarCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original",
                    models.CharField(max_length=600, verbose_name="Sentensa orijinál"),
                ),
                (
                    "corrected",
                    models.CharField(
                        blank=True, max_length=600, verbose_name="Sentensa korreitu"
                    ),
                ),
                (
                    "ok",
                    models.BooleanField(
                        default=False, verbose_name="Sentensa loos ona"
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Rezultadu"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grammar_checks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grammar fix",
                "verbose_name_plural": "Grammar fix",
                "ordering": ["-created_at"],
            },
        ),
    ]
