# Generated by Django 6.1.2 on 2026-10-09 09:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(max_length=300, verbose_name="Pergunta (Inglés)"),
                ),
                ("choice_a", models.CharField(max_length=120, verbose_name="Opsaun A")),
                ("choice_b", models.CharField(max_length=120, verbose_name="Opsaun B")),
                ("choice_c", models.CharField(max_length=120, verbose_name="Opsaun C")),
                ("choice_d", models.CharField(max_length=120, verbose_name="Opsaun D")),
                (
                    "answer",
                    models.CharField(
                        choices=[("a", "A"), ("b", "B"), ("c", "C"), ("d", "D")],
                        max_length=1,
                        verbose_name="Resposta loos",
                    ),
                ),
                (
                    "explanation_tet",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Esplikasaun (Tetun)"
                    ),
                ),
                (
                    "band",
                    models.CharField(
                        choices=[
                            ("beginner", "Hahú (A1-A2)"),
                            ("intermediate", "Média (B1-B2)"),
                            ("advanced", "Avansadu (C1-C2)"),
                        ],
                        default="beginner",
                        max_length=12,
                        verbose_name="Band nível",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativu")),
            ],
            options={
                "verbose_name": "Pergunta quiz",
                "verbose_name_plural": "Pergunta quiz",
                "ordering": ["band", "id"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Hahú"
                    ),
                ),
                ("deadline", models.DateTimeField(verbose_name="Limite oras")),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Remata"),
                ),
                (
                    "question_ids",
                    models.JSONField(default=list, verbose_name="Pergunta"),
                ),
                (
                    "answers",
                    models.JSONField(blank=True, default=dict, verbose_name="Resposta"),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Loos"
                    ),
                ),
                (
                    "total",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Total"),
                ),
                ("late", models.BooleanField(default=False, verbose_name="Liu oras")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Estudante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tentativa quiz",
                "verbose_name_plural": "Tentativa quiz",
                "ordering": ["-started_at"],
            },
        ),
    ]
