# Generated by Django 6.1.2 on 2026-10-09 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tutor", "0002_grammarcheck"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Data",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitor_logs",
                        to="tutor.session",
                        verbose_name="Sesaun",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitor_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Hare husi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log monitorizasaun",
                "verbose_name_plural": "Log monitorizasaun",
                "ordering": ["-viewed_at"],
            },
        ),
    ]
