# Generated by Django 6.1.2 on 2026-10-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tutor_prompt_extra",
                    models.TextField(
                        blank=True,
                        help_text="Ditambah ba prompt dasar (gaya, nada, topiku). Aturan dasar sistema la bele ubah.",
                        max_length=2000,
                        verbose_name="Instrusaun adisionál ba Maun Lafaek",
                    ),
                ),
                (
                    "payments_required",
                    models.BooleanField(
                        default=True,
                        verbose_name="Presiza pakote (se la tika = gratis ba hotu)",
                    ),
                ),
                (
                    "free_turns_per_day",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Dalan gratis kada loron (sein pakote)"
                    ),
                ),
                (
                    "paid_turns_per_day",
                    models.PositiveIntegerField(
                        default=150, verbose_name="Dalan kada loron (ho pakote)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Konfigurasaun sistema",
                "verbose_name_plural": "Konfigurasaun sistema",
            },
        ),
    ]
