# Generated by Django 6.1.2 on 2026-10-09 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title_tet", models.CharField(max_length=80)),
                ("title_en", models.CharField(max_length=80)),
                ("emoji", models.CharField(blank=True, max_length=8)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "band",
                    models.CharField(
                        choices=[
                            ("beginner", "Pemula (A1-A2)"),
                            ("intermediate", "Menengah (B1-B2)"),
                            ("advanced", "Lanjut (C1-C2)"),
                        ],
                        max_length=12,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("title_tet", models.CharField(max_length=100)),
                ("title_en", models.CharField(max_length=100)),
                ("goal_tet", models.TextField()),
                ("goal_en", models.TextField()),
                ("ai_role", models.TextField()),
                ("rubric", models.JSONField(default=list)),
                ("max_turns", models.PositiveSmallIntegerField(default=12)),
                ("is_placement", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="curriculum.scenario",
                    ),
                ),
            ],
            options={
                "ordering": ["scenario__order", "band", "order"],
            },
        ),
    ]
