# Generated by Django 6.1.2 on 2026-10-09 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Kódigu")),
                (
                    "title_tet",
                    models.CharField(max_length=80, verbose_name="Títulu (Tetun)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=80, verbose_name="Títulu (Inglés)"),
                ),
                (
                    "emoji",
                    models.CharField(blank=True, max_length=8, verbose_name="Emoji"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativu")),
            ],
            options={
                "verbose_name": "Situasaun",
                "verbose_name_plural": "Situasaun",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Kódigu")),
                (
                    "band",
                    models.CharField(
                        choices=[
                            ("beginner", "Hahú (A1-A2)"),
                            ("intermediate", "Média (B1-B2)"),
                            ("advanced", "Avansadu (C1-C2)"),
                        ],
                        max_length=12,
                        verbose_name="Band nível",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                (
                    "title_tet",
                    models.CharField(max_length=100, verbose_name="Títulu (Tetun)"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=100, verbose_name="Títulu (Inglés)"),
                ),
                (
                    "goal_tet",
                    models.TextField(verbose_name="Objetivu (Tetun, ba estudante)"),
                ),
                ("goal_en", models.TextField(verbose_name="Objetivu (Inglés, ba AI)")),
                (
                    "ai_role",
                    models.TextField(verbose_name="Papél no situasaun AI (Inglés)"),
                ),
                (
                    "rubric",
                    models.JSONField(
                        default=list, verbose_name="Rubrika avaliasaun (Inglés)"
                    ),
                ),
                (
                    "max_turns",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="Dalan maksimu"
                    ),
                ),
                (
                    "is_placement",
                    models.BooleanField(default=False, verbose_name="Teste nível"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Ativu")),
                (
                    "scenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="curriculum.scenario",
                        verbose_name="Situasaun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Misaun",
                "verbose_name_plural": "Misaun",
                "ordering": ["scenario__order", "band", "order"],
            },
        ),
    ]
