# Generated by Django 6.1.2 on 2026-10-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="is_free",
            field=models.BooleanField(
                default=False, verbose_name="Ngobrol bebas (laiha objetivu)"
            ),
        ),
    ]
