# Generated by Django 6.1.2 on 2026-10-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5, null=True)),
                ("name", models.CharField(max_length=50, verbose_name="Naran")),
                ("hckey", models.CharField(max_length=10, null=True)),
            ],
            options={
                "verbose_name": "Munisipiu",
                "verbose_name_plural": "Munisipiu",
                "ordering": ["name"],
            },
        ),
    ]
